# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: bea92a81e2876a9be47ab5fc8775ffd36ab8589ee96f8971df7ebccbd7cacb2d87279868801e5e8d6e20fded5dc7541284645b40536a1db0be8cc5843cd5e178

test:
  domain_name: example.com 
  secret_key_base: c6b3781dea63b25fc84dc1cc9ddae8e5046c67c1829498502f8a204e9aaf50803cbffef28484d09c3a2272136fde510f15ac4ece004792fabfd2b7af874a1371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
